spring:
  profiles:
    active:
    - dev

#config开发客户端配置信息
---
server:
  port: 7001

spring: 
  profiles: dev
  application: 
    name: springcloud-eureka-config-7001

eureka: 
  client: 
    service-url: 
      defaultZone: http://127.0.0.1:7001/eureka/

#config测试客户端配置信息
---
server: 
  prot: 7001

spring: 
  profiles: test
  application: 
    name: springcloud-eureka-config-7001

eureka: 
  client: 
    service-url: 
      defaultZone: http://127.0.0.1:7001/eureka/
